### ISSUE TITLE
The bloom filter could be better at what it does.

### ISSUE THREAD

**Issue by emilio** [servo/rust-selectors#107]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1336646#c15.

**Comment by emilio** [comment]
(I'll add more details if necessary, I need to run now)

**Comment by SimonSapin** [comment]
I read through some of the linked bug and didn’t really understand what this was about, so please do add more details when you have time :)

**Comment by emilio** [comment]
So the short description is that matches_complex_selector_internal does
something like this:

```
if can_fast_reject() {
  early return
}

start looping through the ancestors/siblings depending on combinator and
then call matches_complex_selector_internal with the rest of the
selector chain.
```

The key here is that we check the bloom filter for _every_ call to
matches_complex_selector internal, when we only really need to check it
once upfront.

The other thing I commented about in that bug is that the current
process of can_fast_reject is as follows:

```
check the rightmost selector entirely, if doesn't match anything,
restart the search if it's recursive, etc.

then check the descendant combinators for the bloom filter.
```

The thing is that matching the rightmost selector _before_ the bloom
filter test makes the selector flags we're adding pretty useless,
because _any_ selector we try to match at that stage can insert flags.

That means that even if we have a hugely nested selector that the bloom
filter is really good at rejecting, like:

    .foo .bar .baz :nth-child(2)

We'll initially attempt to match that :nth-child(2) for every element,
which means that every element we run selector matching on will have the
flags set, which is something the bloom filter would prevent.

The solution to this is moving the bloom filter check to the topmost
non-recursive function and check it only once upfront, and not all the
time.

**Comment by emilio** [comment]
@bholley ^, just in case you're interested on the slightly more detailed description

**Comment by bholley** [comment]
Nice! Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1337541 to track this on the bugzilla side.
