### ISSUE TITLE
Make bloom.rs an independent library

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-selectors#12]
Other bloom filters exist in Rust, but they’re apparently not counting like this one.

Open question: should it also have its own repository, or stay in this one? See #10.

**Comment by SimonSapin** [comment]
The implementations of `BloomHash` for `Atom` and `Namespace` should be behind a Cargo feature, to make the dependency on string-cache optional.

**Comment by jdm** [comment]
Perhaps string-cache should have a feature that makes it depend on the bloom library instead. Dunno.

**Comment by SimonSapin** [comment]
I think this is a general problem with Rust’s trait system. I’ve asked about it: http://internals.rust-lang.org/t/implementing-a-trait-for-a-type-that-don-t-know-about-each-other/1656

**Comment by SimonSapin** [comment]
Let’s not do this:
- Selector matching is the only user in Servo
- I haven’t heard of a request for potential users outside of Servo
- A bloom filter has lots of parameters that can be tuned, and they are hard-coded here, making this library potentially less useful to other users.

(Feel free to re-open if you disagree.)
