### ISSUE TITLE
Reconsider get_link.

### ISSUE THREAD

**Issue by Ms2ger** [servo/rust-selectors#24]
See https://github.com/servo/rust-selectors/pull/23#issuecomment-100640307.

**Comment by SimonSapin** [comment]
`get_link() -> Option<&str>` could be replaced with `is_link() -> bool`, `is_visited_link() -> bool`, and `is_unvisited_link() -> bool`. It’s probably better than trying to deal with browsing history in this library, anyway. How does this sound?

**Comment by Ms2ger** [comment]
WFM
