### ISSUE TITLE
Support ::first-letter pseudo element

### ISSUE THREAD

**Issue by frewsxcv** [servo/rust-selectors#39]
Currently, we just return an error:

https://github.com/servo/rust-selectors/blob/a6cf1fba8f31960254aa62434ab8aeee13aff080/src/parser.rs#L578

http://dev.w3.org/csswg/selectors-3/#first-letter

**Comment by SimonSapin** [comment]
Same comment as https://github.com/servo/rust-selectors/issues/40#issuecomment-122511005

**Comment by SimonSapin** [comment]
Pseudo-element parsing and matching is now generic in this repository, moving to https://github.com/servo/servo/issues/15413.
