### ISSUE TITLE
Support ::first-line pseudo element

### ISSUE THREAD

**Issue by frewsxcv** [servo/rust-selectors#40]
Currently, we just return an error:

https://github.com/servo/rust-selectors/blob/a6cf1fba8f31960254aa62434ab8aeee13aff080/src/parser.rs#L577

http://dev.w3.org/csswg/selectors-3/#first-line

**Comment by SimonSapin** [comment]
Right. But the tricky part is not the parsing here, it’s rather how the cascade and flow construction is affected by this (and `::first-letter`). Until that’s figured out, I’d rather not add parsing support. (If there is a non-Servo user that wants this, we can add parsing support and then reject it in Servo.)

**Comment by frewsxcv** [comment]
I primarily opened these because I noticed they weren't done. I personally have no urgency in completing them, and I have hardly (if ever) seen them used on the web. If you want to close these Issues because realistically you don't think they'll get completed in the near future, go for it.

**Comment by SimonSapin** [comment]
Keeping the issues open is fine.

**Comment by SimonSapin** [comment]
Pseudo-element parsing and matching is now generic in this repository, moving to https://github.com/servo/servo/issues/15413.
